// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8HduBvkD53AT27DvlFpnpHbbyVnt7zOA',
    appId: '1:966805877194:web:2051af9443551b15399f33',
    messagingSenderId: '966805877194',
    projectId: 'prakflutterfirebase-31cdf',
    authDomain: 'prakflutterfirebase-31cdf.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-31cdf.appspot.com',
    measurementId: 'G-0YVYNXBMH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB308K7fGk8dzAgOkWZVQGMjtBszNC6P4I',
    appId: '1:966805877194:android:5da6c4a9069d3833399f33',
    messagingSenderId: '966805877194',
    projectId: 'prakflutterfirebase-31cdf',
    storageBucket: 'prakflutterfirebase-31cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3tSIFYt36PegaP_Y3yyE77SHRVWS_KWI',
    appId: '1:966805877194:ios:cbdcb1882e23cf14399f33',
    messagingSenderId: '966805877194',
    projectId: 'prakflutterfirebase-31cdf',
    storageBucket: 'prakflutterfirebase-31cdf.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3tSIFYt36PegaP_Y3yyE77SHRVWS_KWI',
    appId: '1:966805877194:ios:cbdcb1882e23cf14399f33',
    messagingSenderId: '966805877194',
    projectId: 'prakflutterfirebase-31cdf',
    storageBucket: 'prakflutterfirebase-31cdf.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8HduBvkD53AT27DvlFpnpHbbyVnt7zOA',
    appId: '1:966805877194:web:089229d7b6ee55e3399f33',
    messagingSenderId: '966805877194',
    projectId: 'prakflutterfirebase-31cdf',
    authDomain: 'prakflutterfirebase-31cdf.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-31cdf.appspot.com',
    measurementId: 'G-5XY2WTFCY0',
  );
}
